# --- Bring nft up ---

function configure_nft_up_outside() {
  NS_NAME="$1"
  RULES_FILE="/etc/conf.d/netns/nft-${NS_NAME}-outside.rules"

  if [[ -f "${RULES_FILE}" ]]; then
    # Load the namespace specific nftables rule set.
    nft -f "${RULES_FILE}"
  else
    echo "No netns specific outside rule set found (${RULES_FILE})."
  fi
}

# --- Bring nft down ---

function configure_nft_down_outside() {
  NS_NAME="$1"
  RULES_FILE="/etc/conf.d/netns/nft-${NS_NAME}-outside.rules"
}
