# VETH creates a veth pair of devices (a virtual patch cable between network namespaces).
# The names of two devices can be specified here.
VETH_IFNAME_OUTSIDE=ve-nscodex1
VETH_IFNAME_INSIDE=ve-nscodex2
#
# The IP addresses to use for both devices.
VETH_IFADDR_OUTSIDE=10.0.2.1/24
VETH_IFADDR_INSIDE=10.0.2.2/24

# The inside netns will be nscodex.
